<?php
$title = 'Asian American Dance Theatre';

include '_inc/head.php';

?>

<body class="past-programs">
<div class="page-wrapper">
	<?php include '_inc/header.php'; ?>
	<div id="menu">
	<?php include '_inc/menu.php';?>
	</div>
	<div class="content-wrapper-narrow">
		<h2>Asian American Dance Theatre</h2>
		<p><img src="/_images/AADTs.jpg"></p>
			<p>The Asian American Dance Theatre (AADT) was a unique dance company in New York, active from 1974-1993. Under the direction of Eleanor S. Yung, it was notable for combining two distinct repertoires: a traditional repertoire featuring folk and classical dances from all over Asia and a contemporary repertoire which evokes Asian forms and sensibilities. The AADT performed extensively in the U.S. enthralling audiences of all ages and nationalities. The company performed at the Riverside Dance Festival, Metropolitan Museum of Art, Lincoln Center, New York University, Statue of Liberty, Carver Community Cultural Centre in Texas, Mid-Fest in Ohio, Urban-Fest in North Carolina, and numerous other locales across the country. Ms Yung's contemporary choreography can still be seen on video at the Lincoln Center Library for the Performing Arts. The AADT, founded in 1974, to encompass its many Folk and Visual arts programming, became the AAAC after 1987. 
			<article>
			<p>I founded the Asian American Dance Theatre (AADT) in 1974. There were very few, if any, Asian American public dance performances in New York City at that time. For that matter, there were hardly any traditional Asian dancers actively practicing their art. There was a general misconception and exoticization of traditional Asian dance in the eyes of the public, and very little opportunity for Asian American choreographers to create or showcase their works. </p>
			<p>Dance classes began in the New York Public Library in New York Chinatown, with my friend Fa Ching Chu from Teachers College, teaching community children how to move freely and creatively. A small group of dancers, Lauren Dong, Nancee Sasaki, George Mars, to name a few gathered and we began rehearsals. We rehearsed at Elina Mooney’s beautiful studio on Broome Street, and produced performances with guest choreographers, three of whom in those early years, were Sin Cha Hong, Theodora Yoshikami, and Sharon Hom. Traditional Asian dances were showcased at the library. At that time, there was a Mongolian community in New Jersey where we found a percussionist whom we presented. </p>
			<p>My work “Madhouse” was accepted by Louise Roberts of the Clark Center, and was performed at the Graduate Center on 42nd Street. It received terrible reviews. That did not dampen my purpose and we began our New York Season every year inviting a different guest choreographer to join in, at theaters around the city including Riverside, Marymount, Schimmel, Open Eye, DTW, etc. I received coverage and reviews from New York Times, Post, Daily News, Dance Magazine, Bridge Magazine, and many others.</p>
			<blockquote class="emphasis">
			“American modern and Chinese dance blend in many of her works into theatre that has the urgency of the first and the gestural delicacy of the second.” 
			</blockquote>
			<cite class="attribution">- <a href="http://www.nytimes.com/1984/04/08/arts/the-dance-silk-road-by-miss-yung.html">Jennifer Dunning</a></cite>
			<blockquote class="emphasis">
			“…Its awareness of cross cultural currents makes the Asian American Dance Theatre a fascinating company.” 
			</blockquote>
			<cite class="attribution">- Jack Anderson</cite>
			<blockquote class="emphasis">
			“Yung showed a gracious composure and softness in the plain hand gestures of her absorbing solo ‘Perhaps…’ and ‘The Camp’, the closing piece, was a quietly powerful reminder of the WWII Internment”
			</blockquote>
			<cite class="attribution">- Burt Supree</cite>
			<p>One of the people who saw my works were Richard Lanier of Rockefeller III Fund who spoke to me excitedly after my collaborative piece with my brother Danny, “ID 1,2,3” at Synod House (1976); Dorothy Vislocky of Hunter College who came backstage to congratulate me on “Passage” performed at Riverside (1979), costume designed by Kwok Yee Tai; artist Zhang Hong-tu who painted a backdrop for my piece “Silk Road” (1983) in which Onie Lee had her debut at 4 years of age, and Brooklyn College made a documentary of its production; and David White of DTW who complimented my choreography but said my dancers were not very good. I felt slighted because I love all my dancers. I thought every dancer should have a chance to perform. But I did truly appreciate his enthusiastic comments.</p>
			<p>I won awards from Creative Artists and NEA Dance, and I served on the advisory panels at NEA and NYSCA for many years. My contribution representing the Asian American dance to these funding agencies was limited as my community was small and peripheral, an art form outside the mainstream and rather obscure. The hierarchical order of dance in U.S. culture has always been in descending order - classical ballet, classical modern, contemporary, and the last would be small experimental dance companies of a particular community. While this defines the order of significance of American dance, the questionable category of classical non-western dance in America would fall into Folk Arts. </p>
			<p>Outside the Asian American Dance Theatre, with Saeko Ichinohe, Sun Ock Lee, Reynaldo Alejandro, and myself, we formed the Asian New Dance Coalition in early 1980s, and produced each of our choreographies in our New York seasons. Though short lived, it was a good collaborative representation of Japanese, Korean, Filipino, and myself Chinese American choreographers. </p>
			<p>Of the many activities of the Asian American Dance Theatre, one that stood out in particular was the day long Memorial Performance commemorating the Tiananmen Square Massacres at BMCC Tribeca Theater (1990) featuring Zuni Icosahedron of Hong Kong, and many other artists including Hikari Baba, Fred Houn and Susan Marshall. Marie Alonzo, then company manager did an incredible deed in pulling this together.
			</p>
			<p>At home, we continued presenting traditional Asian dance, in NYC schools, and across the nation. We sought out dancers from Asia, newly immigrated and not able to find venue for their art. Many times, they sought us out. We presented them in lecture demonstrations in elementary and secondary schools, community centers, public libraries. These exquisite dancers were ambassadors of their individual cultures, and often, it would be the first time the audience came into contact with a new culture that they had little knowledge of. The performers in full costume, spoke to them about the art form and the people behind it. In one school, a student came up to Marlene Pitkow, the Program manager at the time, asked her for her autograph, and asked whether we will be performing on Broadway. Instances like this made our day.</p>
			<p>There were many people behind the scenes making this Asian Dance Program both remarkable and memorable. The professionalism and the artistry of all our dancers were impeccable. Dancers such as the Balinese sisters Suarti and Suarni later were recruited by the Asia Society to further its programs. Choreographer/dancers Kuang Yu Fong, Tomie Hahn, Marie Alonzo, Ananya Chatterjea, continued in their respective careers in academia, research, and setting up their own performance companies among other things. They all had great accomplishments after AADT.
			</p>
			<p>Introducing traditional Asian dances was not limited to NYC schools. We also took the company on tour, sometimes together with the contemporary repertoire. Throughout the 80s, we toured to Texas, Ohio, North Carolina, New Mexico, Wisconsin, Michigan, Washington D.C., Pennsylvania, Massachusetts, and others, performing to large audiences, both outdoor and indoor. One noted instance was performances to LGBT audiences at SisterFire in Washington DC, and the Michigan Women’s Music Festival. Another was the Penn State University nine campus tour. </p>
			<p>I am grateful to all the dancers/choreographers/teachers that passed through the Asian American Dance Theatre in both our traditional and contemporary repertoire, at home and on tour. Not in any order, and far from complete are: Wendy Lai, Yen Leung, Wei Xing Xue, Josephine Ting, Mei Hsueh, Helen Tran, Ray Tadio, Nancy Latuja, Kathy Serio, Arundhati Chattopadhyaya, Boon Teo, Dwight Wigfall, Julio Leitao, Najma Ayasha, Janaki Patrick, Young Lan Lee, Muna Tseng, Yung Yung Tsuai, Nayo Takahashi, Haruka Najimi, Lynn Macri, Deena Burton, Vivien Chen, Carla Scheele, Pam Noschese, Annie Bien, and countless more.</p>
			<p>Back at home base, we started the innovative series D’Asia vu, its name credited to Tomie Hahn. It was a showcase of Asian and Asian influenced performances. We presented a wide variety of performance genres, from puppetry, theater, mask dances, a dancer on skates, the Chinese zither guqin, amongst many forms and disciplines. The first D’Asia vu presentation took place at Ilene Pinder’s Balinese American Dance Theater before moving back to our own venue at 26 Bowery. Mary Hays, Director of the New York State Council on the Arts at the time, was in the audience. It is in one of the many D'Asia vu performances, that Kuang Yu Fong premiered her original creation, "A Day at the Office" with a commission grant, and Tomie Hahn first performed her exquisite choreography, "Leaf".</p> 
			<p>At 26 Bowery, we continued our own community school. There were classes in children ballet and creative dance, as well as adult Chinese dance, Jazz, Alexander technique, Jazzercise, Taichi, and in some years by popular demand, ballroom dancing. Memorable are the teachers Nai-Ni Chen, Oilin McBreen, Boon Teo and Yen Leung. Elaine Chu began her connection with me as babysitter at 16, then turned assistant, administrator, bookkeeper for the organization, and finally became School Manager when her own children were attending high school. For many years, we had Annual Dance Recitals, bringing together the children, their parents and the community. We had large coverage from the media, and truly enjoyed being a community arts organization. </p>
			<p>These days I would encounter in Chinatown, parents and grand-parents of former students. They would greet me warmly. It is gratifying to hear one parent telling me how appreciative he is. He credited the growth and success of his children to the weekly classes they attended at the Asian American Dance Theatre/Arts Centre in their formative years. </p>
			These days I would encounter in Chinatown, parents and grand-parents of former students. They would greet me warmly. It is gratifying to hear one parent telling me how appreciative he is. He credited the growth and success of his children to the weekly classes they attended at the Asian American Dance Theatre/Arts Centre in their formative years. 
			</article>
			<p>The Asian American Dance Theatre created and sustained a group of artists who helped identify, preserve and enhance many diverse dance styles that originated in the countries of Asia but that were showcased in communities that seek to understand their place in American culture.  These dancers not only enriched people's sense of their own heritage, they also opened up the understanding of movement and choreographic aesthetics for Americans and artists in general.</p>
			<p>The Asian American Dance Theatre company was notable for its early development and pioneer promotion of contemporary Asian American dance, precursor to many new choreographers of east and west synthesis. Eleanor S. Yung's choreography has yet to be re-discovered: her annual New York Dance Season 1976-90, her cross-country performance tours begun in 1978, her D'Asia Vu choreographer showcase and performance series, and all the traditional and contemporary dancers whom she has helped support.
</p>
	</div>
<div id="mm">
<?php include '_inc/menu.php';?>
</div>
</div>

</body>
</html>

