<?php
$title = 'Artspiral Magazine';
include '_inc/head.php';

?>

<body class="pastprograms">
<div class="page-wrapper">
<?php include '_inc/header.php'; ?>
    <div id="menu">
    <?php include '_inc/menu.php';?>
    </div>
    <main class="content-wrapper narrow">
        <h2>Artspiral Magazine Issue 1</h2>
            <p class="emphasis">Artspiral was a...</p>
            <article>      
            <h3 style="text-transform:none">Negotiating Modernisms: Contemporary Asian Art and The West</h3>
            <h6>Thomas McEvilley, 1996</h6>
            <p>The exhibition Traditions/ Tensions: Contemporary Art from Asia, which was originated by the Asia Society and opened at three venues in New York City in October 1996, contains contemporary art from India, Indonesia, the Philippines, Thailand, and South Korea. The work is “contemporary” not only because it is being made today but also because it is self-consciously historicity in a framework that gives some account of its relationship to the West as well as to its own tradition. I have written elsewhere (Frieze, January 1997) about the exhibition’s structure and some of the artwork in it. Here I would like to mention briefly an important issue that has been in the air for some time but has not been openly discussed enough.</p>
            <p>In 1991 in this publication, Robert Lee conducted an interview with several young artists from a Chinese group called Star Star, which had been formed in 1979, partly in connection with the Democracy Movement. Around 1985, as Sui Kang Zhao, a member of Star Star, said, “The art movement really started... Things were happening so fast, trying to keep up meant breaking through yourself... ” In that year Li Xiaosan wrote an influential article called “The Death of Tradition” in which he argued that every artist should “experiment freely, abandon all strict technical norms and rigid aesthetic standards” in pursuit of a breakthrough into artistic renewal in China. These artists who had come of age after the Cultural Revolution were self-consciously involved with the project of connecting to Euro Modernism. As Wenda Gu, another member of Star Star, put it: “It was revolutionary, it was incredible. Almost 100 years of western modern art repeated itself in only five years in China. Expressionism, Surrealism, Dada, Performance Art, Action Art, everything, everything...”</p>
            <p>Modernism established itself in many countries, and that some of these, not having access to the center of the discourse, remained “marginalized modernism [s].”</p>
            <p>There seemed to be an underlying assumption that to get to Modernism, or Late Modernism, or post-Modernism, one had to go through the West. This assumption is, needless to say, both powerful and controversial. Some of the Asian curatorial advisers who wrote essays in the Traditions/ Tensions catalogue engaged in fascinating ruminations on this issue as they sketched out a spectrum of positions relating to Star Star’s. Indonesian curator and author Jim Supangkat, for example, introduces the useful term “multimodernism.” He points out that Modernism established itself, in one style or another, in many countries, and that some of these, not having access to the center of the discourse, remained “marginalized modernism[s].” Surely he is right about that. Supangkat says that Indonesian Modernism has existed for some time but unacknowledged in Europe and America, the situation is similar for many nations. Several years ago a show called Czech Modernism toured the United States, demonstrating convincingly that Czech culture had participated in the 20th century adventure of Late Modernism, though unacknowledged in the record. I have seen similar exhibitions in Skopje, Macedonia, and Ljubliana, Slovenia, where also highly developed Modernisms existed yet were historically marginalized by various forces-- in these cases above all the Iron Curtain. These marginalized Modernisms were carried out more or less in isolation. Today cultures seeking to enter Modernism or perhaps post -Modernism find easier access to the international discourse.</p>
            <p> The Star Star experience indicates one mode of entering Modernism after being long cut off from it: the accelerated mimesis of Euro- Modernism seen as a short-cut into the present. Like the raft of Buddhism after one has crossed the river, it can be abandoned after its lessons have been learned. Quite another view has been adumbrated by Indian critic Geeta Kapur, who writes that “in order for an African or Asian avant-garde to come into its own, it must ... dismantle the burdensome aspect of Western art, including its endemic vanguardism.” A true avant-garde, she argues, following Peter Burger, “can only be situated in a moment of real historical or political disjunctive.” Thus the avant-garde which began in the United States and Europe not long after World War II is a neo-avant-garde, not the real thing but it seems more plausible if it is applied to the ongoing avant-gardism of the recent American tradition (what Harold Rosenberg called “the tradition of the new”) is, on this view, either a market device or a kind of spastic reflex or morbid repetition compulsion of an Ideological State Apparatus, the foot of a dying rabbit vainly kicking and kicking the air. In pursuing the idea of local avant-gardes (not unlike multi-modernisms) Kapur comes directly to the point: “There is no reason whatsoever.” she writes, “for the rest of the world to subscribe to the vocational stringencies of the American neo-avant-garde.” Indeed, it does seem clear that multimodernisms might arise with their own modes of history, without reference to Euro-Modernism except for the fact that the very idea of history seems to have developed in the West, from Thucydides to Hegel. It is implied that the American model is a burden because it pretends, in tiresome complicity with the long imperial project, to appear as, and to feel itself as, an absolute or universal. “An Indian artist,” Kapur writes “does not aspire to be part of the monumental trans-avant-garde.” Kapur seems clearly right when she observes that “contemporary Euro-American cultural discourse cannot function without a recognition of the major shake ups in its hegemonic assumptions.” But is this a prescription (for the future) or a description (of the recent past)? It seems to refer to what the post-Modern discourse in Europe and the United States has been trying, with deliberation, to accomplish.</p>
            <p>Jae-ryung Roe, writing in a fascinating essay for the Korean position, note that the South Korean government, in 1995, announced a national program of globalization which would amount to “the rebirth of modern Korea.” “An era of globalization, national prosperity, and ultimate unification lay before the Korean people.” There was a background to the moment. After the artistically oppressive post- war period of American occupation, the Infirnel Group ”identified themselves with the postwar generation of European artists and with the movement Art Informal.” Chronologically there is a certain parallel with the emergence of other internationalizing groups in the early post-war period, such as the Bombay Progressives, Subsequently Korean Star Star describes as a hundred years experienced in five: “Op Art, assemblage geometric abstraction, conceptual and performance art.” So Korean artists, like some Chinese, subjected themselves to an initiation into the Western avant-garde canon that Kapur--speaking, of course, from within one of the world’s massively dominant traditions, a global center second to none for ages--declares irrelevant to Indian artists. But that’s not the whole story. In Korea as elsewhere the post-colonial conscience reacted. In the 1980’s the People’s Art movement espoused the belief that “Korean modernism was a result of misguided attempts to mimic the West and a by-product of neocolonialism and cultural imperialism. ” Jae-ryung Roe seems to feel that a kind of synthesis has occurred through a “clear distancing from the past and from the history of modernism, a mastery over the anxieties about the assimilation of Western modernism, and a redemption from the previous obsession with national identity and tradition.” So the confrontation seems to have been fruitful: Modernism redeemed them from their tradition, while their tradition distanced them from Modernism and its anxieties. Still, that is not the whole story either; the attitudes and desires shift back and forth. In 1995 the first Kwangjiu Biennial was huge public success while “many in the Korean art community regarded the biennial as a failure.” “They pointed out that it was not a truly international event, that it lacked overseas promotion and international press coverage, and that it did not succeed in promoting the segehwa [globalization] of Korean art.”</p>
            <p>As Carl Jung once remarked, you never solve your problems, you just outgrow them. In the long run the resolution may look like another detail in the chronology of Chinese contemporary art. A Chinese Dadaist of the 1970’s and 80’s, Huang Yong Ping, put a book titled History of Chinese Painting and a book titled History of Western Painting into a washing machine together. The pages disintegrating in the churning hot soapy water suggested a gradual melt-down of cultural boundaries and a cleansing away of traditional identity in both East and West.</p>
            <p>Huang felt that his idea was equally inspired by western Dadaism and Chinese Zen.</p>
            <p><i>Thomas McEvilley is an Art History professor at Rice University, a contributing editor for Artforum and a senior advisor for Trans. He also contributed to the catalogue accompanying Contemporary Art in Asia: Tradition/Tensions, and spoke at the symposium Fast Forward: The Contemporary Art Scene in Asia.</i></p>
            </article>
            <article>
            <h3 style="text-transform:none">Sleeping with the Enemy: New York Newsday’s Review of Ancestors</h3>
            <h6>Joan Kee, 1996</h6>    
            <p>On Tuesday, May 2, New York Newsday published a review of the exhibition and its key figures, including Director Robert Lee and several participating artists. In it, multiracial artist Yolanda Skeete was quoted as remarking, “Bob Lee is saying, ‘You’re [Skeete] a half-breed, but we love you anyway.” The author, David Garrick also quoted Skeete as saying, “Never before have Chinese held their hands out to an African group like this,” despite the fact that the Ancestors show was a joint African American-Asian American effort. Skeete never made any of these comments. The editorial and management leadership of Newsday did meet with Asian American community leaders and agreed to “look into the matter.” However, neither they nor Garrick could later be reached for comment. This occurred a few months prior to the termination of Newsday’s Manhattan edition.</p>
            <p>While the prominent placement of the article on page 2 and phrases like “ancestral harmony” and “common roots” suggest a step towards the elimination of racism, Newsday’s article is a reminder that racism through words and generalizations still permeate even the supposedly liberal side of the mass media. However, instead of direct name-calling, writers like Gerrick opt to perpetuate racist sentiments by roundabout ways enabling them to escape accusations of racism. Since mass publications like Newsday reach a wide audience, these manifestations of racism can be disseminated over a large area and Newsday’s liberal reputation lend credibility to these racial slurs as acceptable and legitimate expressions. By allowing “half-breed” to infiltrate a major article, Newsday has endorsed racism, and betrayed the ideals of tolerance and harmony it feigns to purport.</p>
            <p>To read the original Newsday article by David Garrick, <a href="/artspiral_magazine/issue_01/garrick.html">click here.</a></p>
            </article> 
            <article>
            <h3 style="text-transform:none">Ethnicity and Abstraction</h3>
            <h6>Luis Camnitzer, 1993</h6>
            <figure class="inline-images">
            <img src="/_images/muhn2.jpg" alt="B.G. Muhn, “Nine Chants,” acrylic on paper, 14 x 10 1/4”">
            <figcaption>B.G. Muhn, “Nine Chants,” acrylic on paper, 14 x 10 1/4”</figcaption>
            </figure>
            <p>When addressing the abstraction/figuration dichotomy the first question is really is the posing of this kind if absolute binary classification responds to a true intellectual need or is an artificial construct. Whichever the conclusion, one can affirm that the polarity is a devilish contraption which marked and contaminated that part of this century’s culture touched in any way by the mainstream and that it did so in all its aspects, not just the visual ones. It was able to mess up any clear thinking about our possibilities for expression since the restriction in the posed options had both political and mercantile origins and consequences. Thus any potentially clear mission for the visual arts in terms of developing ethnic culture has been obscured and eroded. Going beyond these complaints, I also think that any questioning along those lines today, and any excessive preoccupation to find corresponding answers, introduces the danger of blurring a much needed focus on the true needs within the non-mainstream uses of art.</p>

            <p>Abstraction in this century started as utopian, as an eliminator of visual chaos, as a potentially unifying language to transcend the narrow boundaries of provincialism not unlike the claim of mathematics. It came from the same substratum which, fertilized by a “universal ethic,” had led Zamenhof to invent Esperanto towards the end of the nineteenth century. This view, couple with a more specific notion that ethnic awareness is parochial, cemented the prejudice about abstraction being an improper tool for sponsoring issues of identity.</p>

            <p>In defining its own aesthetic enemies, abstractionism went... about to refine its own definition. More than figuration, the target became realism, a term that was politically expedient to lump together the works both Nazi Germany and Stalinist Soviet Union. Thus in the mainstream abstraction stopped being utopian to become an expression of democracy. It grew into an ideology dressed in art, wearing a kind of a uniform which allowed quick recognition without the effort of scholarship. Never mind that the paintings personally made by Hitler, Churchill and Eisenhower all came from the same aesthetic (wrong) corner and never mind all the conundrums posed by Italian fascism. Realism equaled totalitarianism (a cold war term in itself) and abstraction embodied the Western version of freedom to such a degree that it became a USIS tool of propaganda.</p>
            <figure class="inline-images">
            <img src="/_images/KHY.jpg" alt="Hae Yuon Kim, “Home,” 1994, tempera on paper, 40 x 26”">
            <figcaption>Hae Yuon Kim, “Home,” 1994, tempera on paper, 40 x 26”</figcaption>
            </figure>    
            <p>The political opposition wasn’t much better, more subtle or more lucid in its manipulation of aesthetics. From the Soviet point of view, abstraction became the symbol of bourgeois corruption, a symptom of the disintegration of imperialist societies and the neglect of the people. Realism was presented as the only vehicle capable of expressing beauty -- as much in the political as in the visual sense. And beauty, here, was defined as being the “truthful portrayal of life in the Land of the Soviets.”</p>

            <p>To go through an art education in the midst of this cold-war conceptual mess made things quite difficult and even more so on the periphery, where this political polarity arrived very muddled. Some exhibits of abstract art financed by the U.S. travelled through Latin America and arrived in Uruguay while I was an art student. However, the shows were interpreted more as a sign of U.S. national assertion against the School of Paris ... than as a sale of an international concept of freedom. Thus abstraction vs. figuration became primarily a formalist issue, albeit creating violent animosities, where only some Communist Party artist raised ideological issues of the heavy kind.</p>

            <p>Meanwhile, the art school in Uruguay -- as was common in the rest of Latin America -- followed the French Academy model of the nineteenth century well into the 1950s. Realism was espoused pedagogically without registering the new political alliances. This made the academics realism in schools a naive form of realism and the schools themselves both formalist enclaves and a good target for everybody who had any claims on art. Abstractionists attacked the institution for being aesthetically reactionary and anachronistic, communists for its alienation from the people and, finally, students for the close-mindedness of the curriculum. The situation created odd and unstable alliances: abstractionists and students, communists and conservative bourgeoisie, where each constituency had a different agenda in mind. Nobody, fortunately, thought of placing the school in the context of a nazi-communist axis. On the other hand nobody, except for the students, even remotely thought of challenging the institution for being undemocratic. The symbolic value of an art school sponsored by a democratic government overrode any perception of the dogmatism and repressiveness of the educational system, something which at the time was much more tangible to us than any cold-war issue. The fight between abstraction and figuration was bitter, but more informed by strategies for gaining access to the mainstream than to a world order. It was a fight, in fact, that managed to hide many political and philosophical agreements that existed between members of both factions...</p>

            <p>As a student, success was ensured by copying Roman busts for two years. We were then rewarded with the permission to look at real people for the remaining three. The self-perception of the school as a perfect representative of Uruguayan democracy was a problem of a time-warp, not of politics. In fact, the institution was politically so democratic that in spite of the prevailing anticommunist feelings of the government, it maintained political pluralism. One of my teachers, a realist sculptor and an active Party member was famous for continuing his reverence for a Stalin bust in his studio well after Kruschev spilled the beans.</p>

            <p>At age seventeen I was decent in piling up the clay with some respect for general proportions. I had more trouble with the details. People, no matter how much I observed them and how hard I tried, looked much older and rougher in my portrayals than in the mirror. One day I was approached by my Stalin-adoring teacher. He was very upset in ways both memorable and unexpected. He took a deep breath and said: “Listen, I really hate to be in this position and I never would have dreamed of its possibility. But I have to tell you that, even if you may not know it, you are an expressionist. I should not constrain you to just copy the model. Let go and follow your instinct.” His name was Armando Gonzalez and he died some years ago, before his own time-warp disappeared. I learned more from the act of his saying what he said than form what he specifically told me or, for that matter, from expressionism itself. His honesty had not only temporarily conquered his dogma, but it also revealed the stupid manichaeism of the aesthetic positions of the time.</p>

            <p>That was nearly forty years ago, time enough to make us see that we should not continue being faced with the choice between... two formal modes of representation presented as mutually exclusive and which are leftovers of what always was a misleading agenda. The intent of the question here is to elucidate the cultural communication of identity issues and this is so because we are at this point not fertilized by a “universal ethic” but by an “identity ethic.” The simplification of issues into an abstraction vs. figuration equation presumes that dividing art by its appearance rather than by its effect is culturally useful, and it might had been so under the “universal ethic”. In fact, today, it impedes the possibility of seeing art in the light of how it integrates or crosses over with or into everyday life.</p>

            <p>A presumption of simple duality glosses over much more subtle and often contradictory subcategories and ignores the role of meanings and contexts -- the ways things are read. An array of questions immediately comes to mind like: How much is concretism at odds with abstraction? Where are the perceptual limits separating the kitsch of stylization and the efforts of synthesis? How representational do figurative images remain once they are absorbed into patterns? How much figuration do abstract colors have once, like in Byron Kim’s work, they are invested with a pre-knowledge of a meaning? What is the role of abstract “muzak” painting in all of this? How will Mondrian’s work survive the appropriation by L’Oreal shampoo? And even further, how will political correctness survive “benettonism”?</p>

            <p>Then we have the rarely disputed argument that the socalled uneducated viewer is more receptive to figuration than to abstraction. Inasmuch as that is true, a poll among power holders in the governments of the world will prove that this lack of education is not limited to marginalized segments of the... population. And, inasmuch as that is true, it is also the consequence of a miseducation which -- if accepted instead of challenged -- becomes a miseducation perpetuated. But the argument also presumes that in order to consume abstraction one needs a higher degree of sophistication in taste than to consume figuration. Or at least a lesser degree of the perceptual and conceptual laziness which tends to favor narcissistic recognitions. However, this position neglects to recognize that there is as much kitsch or affectation and inauthenticity in the non-figurative arts as in the figurative ones. Education in this context should help in sifting out these issues, no matter what shape they take and address as much the artist as the consumer.</p>

            <p>The concern, in the context of this panel, is primarily with identity issues and cultural self-definition. We are thus presuming that art will deal with the needs for communication with specificity which may override the needs for theoretical speculation. This presumption in turn reveals two hidden ideas: first that we have to deal with narrative elements to somehow be able to pin down identity, and second -- but closely connected -- that theoretical speculation may be a luxury when addressing identity issues.</p>

            <p>In confronting these two ideas we are shifting the focus away from the abstraction/figuration formulation and attempting to bring the analysis into our own agenda. When we speak of narrative quality, it is not in the narrow sense of literature but in the sense of intended vehicles for messages. Art under capitalism, inasmuch as it consists of the production of consumable objects and ideas, serves both to help create culture and to create a market. In economically insolvent areas, the ... primary effect of the cultural production is on the community surrounding the artist and thus has primarily a local importance on within a narrative aura. In the North American and European mainstream traditions the art object bears the artistic value. In peripheral traditions -- both inside and outside the U.S. and Europe, the art object unleashes situations. In her essay for the recent “Latin American Artists of the XXth Century” exhibit in the Museum of Modern Art, Maricarmen Ramirez stresses the need for a departure from the mainstream way of writing the history of art. Referring to conceptualism in Latin America, she points out the need for a new history by establishing a kind of continuity between Mexican Muralism (in her view, a crucial form of Lain American avant-gardism) and the work of Marcel Duchamp, particularly as later understood by Latin American artists. Conceptualism is interesting here because as a category of art it escapes the abstraction/ figuration classification. According to Ramirez, Mexican Muralism can be seen as reinvesting painting with social meaning in a parallel fashion to how later artists reinvested ready made. Ramirez writes:</p>

            <blockquote>In this sense one could argue that if Duchamp’s propositions found a fertile ground in Latin America, it was precisely because the refusal to abandon the specificity and communicative potential of the aesthetic object was deeply embedded in the modern art tradition initiated by Mexican Muralism and extending to this group of political conceptual artists. Duchamp’s radical provocation and subversion of art as an institution, implicit in the creation of the ready-made, is re-enacted in these artist’s work as an ironic tactic aimed at exposing the precariousness of artistic practice itself in the frequently inoperative conditions ... of Latin American periphery. The utilization of the ready-made as a ‘package to communicate ideas’ ultimately points to an underlying concern with the ‘devaluation’ or loss of the natural or symbolic value of the object implicit in any economic of ideological (censored) process of exchange, more than with the process of commodification itself. Therefore, the acts of ‘re-insertion’ or ‘re-positioning’ carried out by these artists, aim at re-investing (or re-humanizing) things with social meaning. The ready-made then, becomes an instrument for the artists’ critical intervention of the real, a strategem to alter patterns of understanding or operation, or a site for recodification of reality. It also becomes a vehicle through which to integrate aesthetic activity with ‘all the systems of reference used in everyday life.’</blockquote>

            <p>It is therefore not anymore an issue of matching visual bits of information between a visible reality and a visible painting or an issue of a neat story line, but one of connectedness between iconography and community. In a slightly more politicized way and with a specific imagery in mind, in 1923 Siqueiros had written for the manifesto of the Mexican Syndicate of Technical Workers, Painters and Sculptors:</p>

            <blockquote>Our fundamental aesthetic goal is to socialized artistic expression. {...} the creators of beauty should apply their greatest energies to work of ideological value for the people, so that the final goal of art, which now is an expression of individualistic masturbation, may be an art for all, of education and of battle.</blockquote>

            <p>While in the context of Siqueiros’ though the statement may have some Stalinist resonance, read at face value, there are issues here that pace us in our reality and force us to deal with the limitations of certain questions, certain answers and certain ways of working.</p>

            <p>The second implication, which may be somewhat worrisome, is .. the implicit preclusion of aesthetic speculations in an art oriented toward cultural self-definition. But this assumption, distorted by the belief that theoretical speculations can only be of a formal nature, views them as happening in isolation from any content or, to be less restrictive, of any concern. However, a concern perceived as relevant within the mainstream may be felt as devoid of any understandable connecting feature within marginalized communities. The parameters of what constitutes pure or theoretical speculation and its importance within a given community can only be assessed by the community itself.</p>

            <p> But even if the assessment could be shared outside the community being addressed, there is an issue of priorities and strategy. Peripheral and marginalized populations are bombarded by mainstream values, stereotypes and expectations. The survival of a stable sense of identity or the development of new values to ensure parallel co-existence as opposed to diminished assimilation is very problematic. Thus, the sense of erosion and the insecurity about the community’s identity will force a definition of art conducive to addressing identity problems and to a new balance of the components used to make art.</p>

            <p>The only freedom we have as artists is the one of deciding in what direction to look. Whichever it is, mainstream or community, we will find expectations, resonance boxes and rewards which will put us into certain modes of production. The options are not based on figuration vs. abstraction. We can be useful or useless within either mainstream or community, so neither abstraction nor figuration can be allowed to be the vehicle for a formula. To chose a style on a formulaic basis can only, in different degrees of blatancy, produce kitsch. ...</p>

            <p>Reviewing Klima’s novel Judge on Trial, John Banville wrote something that seems appropriate, though it may be a tall order for artists:</p>

            <p>“the spiritual quest that its characters are engaged is not a metaphysical struggle for transcendence but a dogged search for a way to live in the here and now with valor and decency, with care for oneself and for others, and with as little self-delusion as possible."</p>

            <p>In some ways it is a nice way of rephrasing what Siqueiros said seventy years ago.    </p>
            </article>

    </main>
<nav role="navigation" id="mm">
<?php include '_inc/menu.php';?>
</nav>
</div>

<script type="text/javascript">
  $(document).ready(function($) {
    $('#accordion').find('.accordion-toggle').click(function(){
      //Expand or collapse this panel
      $(this).next().slideToggle();
      //Hide the other panels if width is large enough
      if ($('.accordion-toggle').width() > 600){
      $(".accordion-content").not($(this).next()).slideUp();
      }
    });
  });
</script>
</body>
</html>

